<?php

declare(strict_types=1);

namespace UncannyPageBuilder\Infrastructure\i18\strings;

final class WorkspaceTabPanelTypographyStrings
{
    /**
     * @return array<string, string>
     */
    public function toArray(): array
    {
        return [
            'appearance' => _x('Appearance', 'Page Builder', 'uncanny-automator'),
            'align' => _x('Align', 'Page Builder', 'uncanny-automator'),
            'alignment' => _x('Alignment', 'Page Builder', 'uncanny-automator'),
            'align_left_action' => _x('Align text left', 'Page Builder', 'uncanny-automator'),
            'align_center_action' => _x('Align text center', 'Page Builder', 'uncanny-automator'),
            'align_right_action' => _x('Align text right', 'Page Builder', 'uncanny-automator'),
            'align_justify_action' => _x('Justify text', 'Page Builder', 'uncanny-automator'),
            'case' => _x('Case', 'Page Builder', 'uncanny-automator'),
            'color' => _x('Color', 'Page Builder', 'uncanny-automator'),
            'computed_details' => _x('Computed details', 'Page Builder', 'uncanny-automator'),
            'decoration' => _x('Decoration', 'Page Builder', 'uncanny-automator'),
            'decoration_color' => _x('Decoration color', 'Page Builder', 'uncanny-automator'),
            'decoration_thickness' => _x('Decoration thickness', 'Page Builder', 'uncanny-automator'),
            'effects' => _x('Effects', 'Page Builder', 'uncanny-automator'),
            'family' => _x('Family', 'Page Builder', 'uncanny-automator'),
            'fill_color' => _x('Fill color', 'Page Builder', 'uncanny-automator'),
            'font' => _x('Font', 'Page Builder', 'uncanny-automator'),
            'font_family' => _x('Font family', 'Page Builder', 'uncanny-automator'),
            'font_size' => _x('Font size', 'Page Builder', 'uncanny-automator'),
            'font_weight' => _x('Font weight', 'Page Builder', 'uncanny-automator'),
            'line_height' => _x('Line height', 'Page Builder', 'uncanny-automator'),
            'measure' => _x('Measure', 'Page Builder', 'uncanny-automator'),
            'raw_color' => _x('Raw color', 'Page Builder', 'uncanny-automator'),
            'raw_css' => _x('Raw CSS', 'Page Builder', 'uncanny-automator'),
            'raw_decoration_color' => _x('Raw text-decoration-color', 'Page Builder', 'uncanny-automator'),
            'raw_decoration_line' => _x('Raw text-decoration-line', 'Page Builder', 'uncanny-automator'),
            'raw_decoration_thickness' => _x('Raw text-decoration-thickness', 'Page Builder', 'uncanny-automator'),
            'raw_font_family' => _x('Raw font-family', 'Page Builder', 'uncanny-automator'),
            'raw_font_size' => _x('Raw font-size', 'Page Builder', 'uncanny-automator'),
            'raw_font_style' => _x('Raw font-style', 'Page Builder', 'uncanny-automator'),
            'raw_font_variant' => _x('Raw font-variant', 'Page Builder', 'uncanny-automator'),
            'raw_font_weight' => _x('Raw font-weight', 'Page Builder', 'uncanny-automator'),
            'raw_letter_spacing' => _x('Raw letter-spacing', 'Page Builder', 'uncanny-automator'),
            'raw_line_height' => _x('Raw line-height', 'Page Builder', 'uncanny-automator'),
            'raw_text_align' => _x('Raw text-align', 'Page Builder', 'uncanny-automator'),
            'raw_text_transform' => _x('Raw text-transform', 'Page Builder', 'uncanny-automator'),
            'raw_white_space' => _x('Raw white-space', 'Page Builder', 'uncanny-automator'),
            'raw_word_spacing' => _x('Raw word-spacing', 'Page Builder', 'uncanny-automator'),
            'spacing' => _x('Spacing', 'Page Builder', 'uncanny-automator'),
            'size' => _x('Size', 'Page Builder', 'uncanny-automator'),
            'stroke_color' => _x('Stroke color', 'Page Builder', 'uncanny-automator'),
            'style' => _x('Style', 'Page Builder', 'uncanny-automator'),
            'text_alignment' => _x('Text alignment', 'Page Builder', 'uncanny-automator'),
            'text_color' => _x('Text color', 'Page Builder', 'uncanny-automator'),
            'transform' => _x('Transform', 'Page Builder', 'uncanny-automator'),
            'typography' => _x('Typography', 'Page Builder', 'uncanny-automator'),
            'weight' => _x('Weight', 'Page Builder', 'uncanny-automator'),
            'white_space' => _x('White space', 'Page Builder', 'uncanny-automator'),
            'word_spacing' => _x('Word spacing', 'Page Builder', 'uncanny-automator'),
            'align_start' => _x('Start', 'Page Builder', 'uncanny-automator'),
            'align_left' => _x('Left', 'Page Builder', 'uncanny-automator'),
            'align_center' => _x('Center', 'Page Builder', 'uncanny-automator'),
            'align_right' => _x('Right', 'Page Builder', 'uncanny-automator'),
            'align_end' => _x('End', 'Page Builder', 'uncanny-automator'),
            'align_justify' => _x('Justify', 'Page Builder', 'uncanny-automator'),
            'font_weight_100' => _x('Thin 100', 'Page Builder', 'uncanny-automator'),
            'font_weight_200' => _x('Extra light 200', 'Page Builder', 'uncanny-automator'),
            'font_weight_300' => _x('Light 300', 'Page Builder', 'uncanny-automator'),
            'font_weight_400' => _x('Regular 400', 'Page Builder', 'uncanny-automator'),
            'font_weight_500' => _x('Medium 500', 'Page Builder', 'uncanny-automator'),
            'font_weight_600' => _x('Semi bold 600', 'Page Builder', 'uncanny-automator'),
            'font_weight_700' => _x('Bold 700', 'Page Builder', 'uncanny-automator'),
            'font_weight_800' => _x('Extra bold 800', 'Page Builder', 'uncanny-automator'),
            'font_weight_900' => _x('Black 900', 'Page Builder', 'uncanny-automator'),
            'font_style_normal' => _x('Normal', 'Page Builder', 'uncanny-automator'),
            'font_style_italic' => _x('Italic', 'Page Builder', 'uncanny-automator'),
            'font_style_oblique' => _x('Oblique', 'Page Builder', 'uncanny-automator'),
            'text_transform_none' => _x('None', 'Page Builder', 'uncanny-automator'),
            'text_transform_uppercase' => _x('Uppercase', 'Page Builder', 'uncanny-automator'),
            'text_transform_lowercase' => _x('Lowercase', 'Page Builder', 'uncanny-automator'),
            'text_transform_capitalize' => _x('Capitalize', 'Page Builder', 'uncanny-automator'),
            'white_space_normal' => _x('Normal', 'Page Builder', 'uncanny-automator'),
            'white_space_nowrap' => _x('No wrap', 'Page Builder', 'uncanny-automator'),
            'white_space_pre' => _x('Pre', 'Page Builder', 'uncanny-automator'),
            'white_space_pre_wrap' => _x('Pre wrap', 'Page Builder', 'uncanny-automator'),
            'white_space_pre_line' => _x('Pre line', 'Page Builder', 'uncanny-automator'),
            'white_space_break_spaces' => _x('Break spaces', 'Page Builder', 'uncanny-automator'),
            'decoration_line_none' => _x('None', 'Page Builder', 'uncanny-automator'),
            'decoration_line_underline' => _x('Underline', 'Page Builder', 'uncanny-automator'),
            'decoration_line_overline' => _x('Overline', 'Page Builder', 'uncanny-automator'),
            'decoration_line_line-through' => _x('Line through', 'Page Builder', 'uncanny-automator'),
        ];
    }
}
