<?php

declare(strict_types=1);

namespace UncannyPageBuilder\Infrastructure\i18\strings;

final class WorkspaceTabPanelTokenStrings
{
    /**
     * @return array<string, string>
     */
    public function toArray(): array
    {
        return [
            'colors' => _x('Colors', 'Page Builder', 'uncanny-automator'),
            'custom_font' => _x('Custom font', 'Page Builder', 'uncanny-automator'),
            'custom_font_hint' => _x('For fonts not in the list, e.g. Georgia, serif.', 'Page Builder', 'uncanny-automator'),
            'custom_font_value_hint' => _x('Type a custom value below', 'Page Builder', 'uncanny-automator'),
            /* translators: %s: Custom font value entered by the user. */
            'custom_value' => _x('Custom value: %s', 'Page Builder', 'uncanny-automator'),
            'fallback_origin' => _x('Fallback', 'Page Builder', 'uncanny-automator'),
            'global_origin' => _x('Brand styles', 'Page Builder', 'uncanny-automator'),
            'inherit_global_role' => _x('Inherit Brand styles', 'Page Builder', 'uncanny-automator'),
            /* translators: %s: Inherited font label. */
            'inherit_value' => _x('Inherit: %s', 'Page Builder', 'uncanny-automator'),
            'inherited_origin' => _x('Inherited', 'Page Builder', 'uncanny-automator'),
            'page_origin' => _x('Page', 'Page Builder', 'uncanny-automator'),
            'reset' => _x('Reset', 'Page Builder', 'uncanny-automator'),
            'tokens_fallback_title' => _x('Tokens', 'Page Builder', 'uncanny-automator'),
            'typography' => _x('Typography', 'Page Builder', 'uncanny-automator'),
            'token_group_theme-colors' => _x('Brand colors', 'Page Builder', 'uncanny-automator'),
            'token_group_body' => _x('Body', 'Page Builder', 'uncanny-automator'),
            'token_group_links' => _x('Links', 'Page Builder', 'uncanny-automator'),
            'token_group_headings' => _x('Headings', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-primary' => _x('Primary', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-secondary' => _x('Secondary', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-success' => _x('Success', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-info' => _x('Info', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-warning' => _x('Warning', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-danger' => _x('Danger', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-light' => _x('Light', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-dark' => _x('Dark', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-body-font-family' => _x('Body font family', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-body-font-size' => _x('Body font size', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-body-font-weight' => _x('Body font weight', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-body-line-height' => _x('Body line height', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-body-color' => _x('Body color', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-body-bg' => _x('Body background', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-link-color' => _x('Link color', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-link-hover-color' => _x('Link hover color', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-heading-color' => _x('Heading color', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-heading-font-family' => _x('Headings font family', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-heading-font-weight' => _x('Headings font weight', 'Page Builder', 'uncanny-automator'),
            'token_field_--bs-heading-line-height' => _x('Headings line height', 'Page Builder', 'uncanny-automator'),
            'typography_role_body_label' => _x('Body', 'Page Builder', 'uncanny-automator'),
            'typography_role_body_description' => _x('Default site text', 'Page Builder', 'uncanny-automator'),
            'typography_role_body_preview' => _x('Build pages that feel readable from the first paragraph.', 'Page Builder', 'uncanny-automator'),
            'typography_role_paragraph_label' => _x('Paragraph', 'Page Builder', 'uncanny-automator'),
            'typography_role_paragraph_description' => _x('Long-form paragraph text', 'Page Builder', 'uncanny-automator'),
            'typography_role_paragraph_preview' => _x('Use this role when paragraph copy needs its own cadence.', 'Page Builder', 'uncanny-automator'),
            'typography_role_headings_label' => _x('Headings', 'Page Builder', 'uncanny-automator'),
            'typography_role_headings_description' => _x('Shared heading typography', 'Page Builder', 'uncanny-automator'),
            'typography_role_headings_preview' => _x('Heading preview', 'Page Builder', 'uncanny-automator'),
            'typography_role_h1_label' => _x('H1', 'Page Builder', 'uncanny-automator'),
            'typography_role_h1_description' => _x('Top-level display size', 'Page Builder', 'uncanny-automator'),
            'typography_role_h1_preview' => _x('Hero headline', 'Page Builder', 'uncanny-automator'),
            'typography_role_h2_label' => _x('H2', 'Page Builder', 'uncanny-automator'),
            'typography_role_h2_description' => _x('Section title size', 'Page Builder', 'uncanny-automator'),
            'typography_role_h2_preview' => _x('Section heading', 'Page Builder', 'uncanny-automator'),
            'typography_role_h3_label' => _x('H3', 'Page Builder', 'uncanny-automator'),
            'typography_role_h3_description' => _x('Subsection title size', 'Page Builder', 'uncanny-automator'),
            'typography_role_h3_preview' => _x('Subsection heading', 'Page Builder', 'uncanny-automator'),
            'typography_role_h4_label' => _x('H4', 'Page Builder', 'uncanny-automator'),
            'typography_role_h4_description' => _x('Utility heading size', 'Page Builder', 'uncanny-automator'),
            'typography_role_h4_preview' => _x('Utility heading', 'Page Builder', 'uncanny-automator'),
            'typography_role_h5_label' => _x('H5', 'Page Builder', 'uncanny-automator'),
            'typography_role_h5_description' => _x('Small heading size', 'Page Builder', 'uncanny-automator'),
            'typography_role_h5_preview' => _x('Small heading', 'Page Builder', 'uncanny-automator'),
            'typography_role_h6_label' => _x('H6', 'Page Builder', 'uncanny-automator'),
            'typography_role_h6_description' => _x('Micro heading size', 'Page Builder', 'uncanny-automator'),
            'typography_role_h6_preview' => _x('Micro heading', 'Page Builder', 'uncanny-automator'),
            'typography_role_buttons_label' => _x('Buttons', 'Page Builder', 'uncanny-automator'),
            'typography_role_buttons_description' => _x('Calls to action and buttons', 'Page Builder', 'uncanny-automator'),
            'typography_role_buttons_preview' => _x('Primary action', 'Page Builder', 'uncanny-automator'),
            'typography_role_navigation_label' => _x('Navigation', 'Page Builder', 'uncanny-automator'),
            'typography_role_navigation_description' => _x('Menus and navigation labels', 'Page Builder', 'uncanny-automator'),
            'typography_role_navigation_preview' => _x('Home  About  Contact', 'Page Builder', 'uncanny-automator'),
            'typography_role_blockquote_label' => _x('Blockquote', 'Page Builder', 'uncanny-automator'),
            'typography_role_blockquote_description' => _x('Quoted content', 'Page Builder', 'uncanny-automator'),
            'typography_role_blockquote_preview' => _x('“Strong typography makes the layout feel intentional.”', 'Page Builder', 'uncanny-automator'),
            'typography_role_code_label' => _x('Code', 'Page Builder', 'uncanny-automator'),
            'typography_role_code_description' => _x('Code, keyboard, and monospace text', 'Page Builder', 'uncanny-automator'),
            'typography_role_code_preview' => _x('const heading = "Code preview";', 'Page Builder', 'uncanny-automator'),
            'typography_role_caption_label' => _x('Captions and labels', 'Page Builder', 'uncanny-automator'),
            'typography_role_caption_description' => _x('Helper text and metadata', 'Page Builder', 'uncanny-automator'),
            'typography_role_caption_preview' => _x('Helpful details live here.', 'Page Builder', 'uncanny-automator'),
            'typography_field_font_family' => _x('Font family', 'Page Builder', 'uncanny-automator'),
            'typography_field_font_size' => _x('Font size', 'Page Builder', 'uncanny-automator'),
            'typography_field_font_weight' => _x('Font weight', 'Page Builder', 'uncanny-automator'),
            'typography_field_line_height' => _x('Line height', 'Page Builder', 'uncanny-automator'),
            'typography_field_font_style' => _x('Font style', 'Page Builder', 'uncanny-automator'),
            'typography_field_letter_spacing' => _x('Letter spacing', 'Page Builder', 'uncanny-automator'),
            'typography_field_text_transform' => _x('Text transform', 'Page Builder', 'uncanny-automator'),
            'typography_font_weight_100' => _x('Thin 100', 'Page Builder', 'uncanny-automator'),
            'typography_font_weight_200' => _x('Extra light 200', 'Page Builder', 'uncanny-automator'),
            'typography_font_weight_300' => _x('Light 300', 'Page Builder', 'uncanny-automator'),
            'typography_font_weight_400' => _x('Regular 400', 'Page Builder', 'uncanny-automator'),
            'typography_font_weight_500' => _x('Medium 500', 'Page Builder', 'uncanny-automator'),
            'typography_font_weight_600' => _x('Semi bold 600', 'Page Builder', 'uncanny-automator'),
            'typography_font_weight_700' => _x('Bold 700', 'Page Builder', 'uncanny-automator'),
            'typography_font_weight_800' => _x('Extra bold 800', 'Page Builder', 'uncanny-automator'),
            'typography_font_weight_900' => _x('Black 900', 'Page Builder', 'uncanny-automator'),
            'typography_font_style_normal' => _x('Normal', 'Page Builder', 'uncanny-automator'),
            'typography_font_style_italic' => _x('Italic', 'Page Builder', 'uncanny-automator'),
            'typography_font_style_oblique' => _x('Oblique', 'Page Builder', 'uncanny-automator'),
            'typography_text_transform_none' => _x('None', 'Page Builder', 'uncanny-automator'),
            'typography_text_transform_uppercase' => _x('Uppercase', 'Page Builder', 'uncanny-automator'),
            'typography_text_transform_lowercase' => _x('Lowercase', 'Page Builder', 'uncanny-automator'),
            'typography_text_transform_capitalize' => _x('Capitalize', 'Page Builder', 'uncanny-automator'),
        ];
    }
}
