<?php

declare(strict_types=1);

namespace UncannyPageBuilder\Infrastructure\i18\strings;

final class WorkspaceTabPanelBackgroundStrings
{
    /**
     * @return array<string, string>
     */
    public function toArray(): array
    {
        return [
            'attachment_fixed' => _x('Fixed', 'Page Builder', 'uncanny-automator'),
            'attachment_local' => _x('Local', 'Page Builder', 'uncanny-automator'),
            'attachment_scroll' => _x('Scroll', 'Page Builder', 'uncanny-automator'),
            'background' => _x('Background', 'Page Builder', 'uncanny-automator'),
            'background_color' => _x('Background color', 'Page Builder', 'uncanny-automator'),
            'background_fill' => _x('Background fill', 'Page Builder', 'uncanny-automator'),
            'background_image' => _x('Background image', 'Page Builder', 'uncanny-automator'),
            'blend_color' => _x('Color', 'Page Builder', 'uncanny-automator'),
            'blend_color_burn' => _x('Color burn', 'Page Builder', 'uncanny-automator'),
            'blend_color_dodge' => _x('Color dodge', 'Page Builder', 'uncanny-automator'),
            'blend_darken' => _x('Darken', 'Page Builder', 'uncanny-automator'),
            'blend_difference' => _x('Difference', 'Page Builder', 'uncanny-automator'),
            'blend_exclusion' => _x('Exclusion', 'Page Builder', 'uncanny-automator'),
            'blend_hard_light' => _x('Hard light', 'Page Builder', 'uncanny-automator'),
            'blend_hue' => _x('Hue', 'Page Builder', 'uncanny-automator'),
            'blend_lighten' => _x('Lighten', 'Page Builder', 'uncanny-automator'),
            'blend_luminosity' => _x('Luminosity', 'Page Builder', 'uncanny-automator'),
            'blend_multiply' => _x('Multiply', 'Page Builder', 'uncanny-automator'),
            'blend_normal' => _x('Normal', 'Page Builder', 'uncanny-automator'),
            'blend_overlay' => _x('Overlay', 'Page Builder', 'uncanny-automator'),
            'blend_saturation' => _x('Saturation', 'Page Builder', 'uncanny-automator'),
            'blend_screen' => _x('Screen', 'Page Builder', 'uncanny-automator'),
            'blend_soft_light' => _x('Soft light', 'Page Builder', 'uncanny-automator'),
            'clip_border_box' => _x('Border box', 'Page Builder', 'uncanny-automator'),
            'clip_content_box' => _x('Content box', 'Page Builder', 'uncanny-automator'),
            'clip_padding_box' => _x('Padding box', 'Page Builder', 'uncanny-automator'),
            'clip_text' => _x('Text', 'Page Builder', 'uncanny-automator'),
            'computed_attachment' => _x('Attachment', 'Page Builder', 'uncanny-automator'),
            'computed_blend_mode' => _x('Blend mode', 'Page Builder', 'uncanny-automator'),
            'computed_clip' => _x('Clip', 'Page Builder', 'uncanny-automator'),
            'computed_color' => _x('Color', 'Page Builder', 'uncanny-automator'),
            'computed_image' => _x('Image', 'Page Builder', 'uncanny-automator'),
            'computed_origin' => _x('Origin', 'Page Builder', 'uncanny-automator'),
            'computed_position' => _x('Position', 'Page Builder', 'uncanny-automator'),
            'computed_repeat' => _x('Repeat', 'Page Builder', 'uncanny-automator'),
            'computed_size' => _x('Size', 'Page Builder', 'uncanny-automator'),
            'computed_details' => _x('Computed details', 'Page Builder', 'uncanny-automator'),
            'custom' => _x('Custom', 'Page Builder', 'uncanny-automator'),
            'custom_position' => _x('Custom position', 'Page Builder', 'uncanny-automator'),
            'custom_size' => _x('Custom size', 'Page Builder', 'uncanny-automator'),
            'fill' => _x('Fill', 'Page Builder', 'uncanny-automator'),
            'fill_color_confirm' => _x('Changing the fill color will remove the active background image or gradient. Continue?', 'Page Builder', 'uncanny-automator'),
            'fill_color_warning' => _x('Changing the fill color will remove the active background image or gradient.', 'Page Builder', 'uncanny-automator'),
            'fit_position' => _x('Fit & Position', 'Page Builder', 'uncanny-automator'),
            'focal_point' => _x('Focal point', 'Page Builder', 'uncanny-automator'),
            'gradient' => _x('Gradient', 'Page Builder', 'uncanny-automator'),
            'image' => _x('Image', 'Page Builder', 'uncanny-automator'),
            'image_url' => _x('Image URL', 'Page Builder', 'uncanny-automator'),
            'media_unavailable_message' => _x('WordPress media library is not available.', 'Page Builder', 'uncanny-automator'),
            'no_image_selected' => _x('No image selected', 'Page Builder', 'uncanny-automator'),
            'none' => _x('None', 'Page Builder', 'uncanny-automator'),
            'origin_border_box' => _x('Border box', 'Page Builder', 'uncanny-automator'),
            'origin_content_box' => _x('Content box', 'Page Builder', 'uncanny-automator'),
            'origin_padding_box' => _x('Padding box', 'Page Builder', 'uncanny-automator'),
            'painting_options' => _x('Painting options', 'Page Builder', 'uncanny-automator'),
            'choose_image' => _x('Choose image', 'Page Builder', 'uncanny-automator'),
            'position_center_bottom' => _x('Center bottom', 'Page Builder', 'uncanny-automator'),
            'position_center_center' => _x('Center center', 'Page Builder', 'uncanny-automator'),
            'position_center_top' => _x('Center top', 'Page Builder', 'uncanny-automator'),
            'position_left_bottom' => _x('Left bottom', 'Page Builder', 'uncanny-automator'),
            'position_left_center' => _x('Left center', 'Page Builder', 'uncanny-automator'),
            'position_left_top' => _x('Left top', 'Page Builder', 'uncanny-automator'),
            'position_right_bottom' => _x('Right bottom', 'Page Builder', 'uncanny-automator'),
            'position_right_center' => _x('Right center', 'Page Builder', 'uncanny-automator'),
            'position_right_top' => _x('Right top', 'Page Builder', 'uncanny-automator'),
            'raw_css' => _x('Raw CSS', 'Page Builder', 'uncanny-automator'),
            'raw_background_image' => _x('Raw background-image', 'Page Builder', 'uncanny-automator'),
            'raw_background_position' => _x('Raw background-position', 'Page Builder', 'uncanny-automator'),
            'raw_background_repeat' => _x('Raw background-repeat', 'Page Builder', 'uncanny-automator'),
            'raw_background_size' => _x('Raw background-size', 'Page Builder', 'uncanny-automator'),
            'repeat' => _x('Repeat', 'Page Builder', 'uncanny-automator'),
            'repeat_no' => _x('No repeat', 'Page Builder', 'uncanny-automator'),
            'repeat_round' => _x('Round', 'Page Builder', 'uncanny-automator'),
            'repeat_space' => _x('Space', 'Page Builder', 'uncanny-automator'),
            'repeat_x' => _x('Repeat X', 'Page Builder', 'uncanny-automator'),
            'repeat_y' => _x('Repeat Y', 'Page Builder', 'uncanny-automator'),
            'select_background_image' => _x('Select background image', 'Page Builder', 'uncanny-automator'),
            'select_image' => _x('Select image', 'Page Builder', 'uncanny-automator'),
            'size_auto' => _x('Auto', 'Page Builder', 'uncanny-automator'),
            'size_contain' => _x('Contain', 'Page Builder', 'uncanny-automator'),
            'size_cover' => _x('Cover', 'Page Builder', 'uncanny-automator'),
            'remove_image' => _x('Remove image', 'Page Builder', 'uncanny-automator'),
            'type' => _x('Type', 'Page Builder', 'uncanny-automator'),
        ];
    }
}
