name: Convert readme.txt to README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # or your preferred version

      - name: Install Composer dependencies
        run: |
          composer require wpreadme2markdown/wp2md --no-progress --no-scripts
          composer install --ignore-platform-reqs

      - name: Convert readme.txt to README.md
        run: vendor/bin/wp2md -s uncanny-automator -i readme.txt -o README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if [[ `git status --porcelain` ]]; then
            git add README.md
            git commit -m "Auto-convert readme.txt to README.md"
            git push
          else
            echo "No changes to commit."
          fi
